### ISSUE TITLE
方法是不是都用不了了

### ISSUE THREAD

**Issue by 1von** [hecheng1996lzg/damedane#5]
方法1，f12运行后，仍然弹出时间确认窗口
方法2，点开始后，打开新页面，随后就自动关闭了，啥都没有，视频播放界面也没有…
有精力的话，希望能更新一下

**Comment by hecheng1996lzg** [comment]
记不清了，方法2得先添加视频保证学习中心有视频列表，添加的视频也必须是纯视频，那些可以内部翻页点击看ppt的视频是没办法自动播放的

**Comment by 1von** [comment]
好吧get了
